AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - 'db/schema.rb'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

