AllCops:
  Exclude:
    - 'config/initializers/secret_token.rb'
    - 'db/schema.rb'
    - '**/*.gemfile'
    - '**/Gemfile'
    - '**/gems.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/LineLength:
  Enabled: true
  Max: 120

## Style

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: '#percent-i'
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

