language: ruby
rvm:
  - 2.5.1

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec

before_script:
  - psql -c 'create database flashcards_test;' -U postgres
  - cp config/database.travis.yml config/database.yml


